Repository mschermann/data_viz_reader, pull requests merged in 2019-04, with the labels that each got.

#979 Update 02-fundamentals.Rmd
  02-fundamentals.Rmd
Labels: grammatical

#964 issue #889 fixed
  book.bib
Labels: bug, enhancement

#962 Deleting the dupilicated contents
  01-intro.Rmd
Labels: duplicate

#961 Part1 - Restructure and expand section 5.3 (chapter5)#775
  .Rapp.history
  04-patterns.Rmd
  book.bib
  images/.DS_Store
Labels: enhancement

#941 Added the images for Section 2.1
  01-intro.Rmd
  book.bib
  images/Exploratory.png
  images/Presentation.jpg
  images/confirmatory.png
Labels: enhancement

#1007 Fixed issue#785 - Section 6.6 content does not belong to Data Ethics
  03-casestudies.Rmd
  05-ethics.Rmd
Labels: enhancement

#1047 Update 02-fundamentals.Rmd Issue #1044
  02-fundamentals.Rmd
Labels: enhancement

#1008 Strivedi2 fixing issue #771
  index.Rmd
Labels: grammatical

#1049 fixed issue #914 & issue #901
  06-conclusion.Rmd
  book.bib
Labels: enhancement

#1019 4.5.3 graphic(Usage of plastic in last few decades) changes
  03-casestudies.Rmd
  book.bib
  images/Global-plastic-production-1917-to-2017.png
Labels: enhancement

#999 #758 Updated the picture for 4.2.3
  03-casestudies.Rmd
  images/uber_map.png
Labels: enhancement

#1016 Harizhisham 917
  05-ethics.Rmd
  data_viz_reader.log
  data_viz_reader.tex
  docs/case-studies.html
  docs/conclusion.html
  docs/data_viz_reader_files/figure-html/Outliar Detection-1.png
  docs/data_viz_reader_files/figure-html/Outliar Detection2-1.png
  docs/data_viz_reader_files/figure-html/nice-fig-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-1-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-2-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-2-2.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-20-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-22-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-4-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-5-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-6-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-7-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-8-1.png
  docs/data_viz_reader_files/figure-html/unnamed-chunk-9-1.png
  docs/ethics.html
  docs/fundamentals.html
  docs/index.html
  docs/introduction.html
  docs/patterns.html
  docs/references-1.html
  docs/search_index.json
  images/common-injuries.png
Labels: reference issue

#1042 Update 02-fundamentals.Rmd - Fixed issue #867
  02-fundamentals.Rmd
  book.bib
  images/scatterplot_bigdot.png
  images/scatterplot_smalldot.png
Labels: enhancement

#1048 Solution for issue #916
  book.bib
Labels: enhancement

#1059 Update 01-intro.Rmd, Issue #807 rephrase paragraph
  01-intro.Rmd
Labels: enhancement, grammatical

#1060 Fix for issue #878
  01-intro.Rmd
Labels: enhancement

#1091 Update 03-casestudies.Rmd - Fix formatting
  03-casestudies.Rmd
Labels: enhancement

#1095 Update 02-fundamentals.Rmd - Fix formatting
  02-fundamentals.Rmd
Labels: enhancement

#1110 Update book.bib (Issue#933)
  book.bib
Labels: invalid

#1109 Issue(#779) Update 02-fundamentals.Rmd
  02-fundamentals.Rmd
Labels: bug

#1120 Fixed Format/Source Issue in Malaria Case Study
  03-casestudies.Rmd
Labels: enhancement

#1096 Update 02-fundamentals.Rmd
  02-fundamentals.Rmd
Labels: enhancement, grammatical

#1129 Update 02-fundamentals.Rmd
  02-fundamentals.Rmd
Labels: enhancement

#1092 Attempt to Fix issue #883
  01-intro.Rmd
Labels: enhancement
