Repository mschermann/data_viz_reader, pull requests merged in 2019-05, with the labels that each got.

#1149 Fixing issue #865
  01-intro.Rmd
Labels: enhancement

#1150 Fixed issue #1072 and #1073
  01-intro.Rmd
  02-fundamentals.Rmd
Labels: duplicate, enhancement

#1156 1099 fix section 7.1
  06-conclusion.Rmd
  book.bib
Labels: enhancement

#1163 Added a subsection that illustrates good and bad examples of maps.Issue #913
  04-patterns.Rmd
  book.bib
  images/map_colors.png
  images/map_hogs.png
  images/profit_ratio.png
  images/profit_ratio_map.png
Labels: enhancement, help wanted

#1152 Content proposal for 5.2.5 Audience Perspective
  04-patterns.Rmd
  images/56857056-5c004380-691d-11e9-90f0-4bb8a9e5bab6.png
  images/56857069-979b0d80-691d-11e9-8e2c-24fa0e32c447.png
Labels: enhancement

#1153 Addition of new content under chapter 6: Ethics
  05-ethics.Rmd
  book.bib
Labels: enhancement

#1168 Update Content of Color
  04-patterns.Rmd
Labels: enhancement

#1178 Update 01-Intro.rmd Content Proposal
  01-intro.Rmd
  book.bib
  images/hans_world_health_chart.png
Labels: enhancement

#1159 Update 02-fundamentals.Rmd
  02-fundamentals.Rmd
Labels: enhancement

#1167 2.2.0.1 Importance of Data Exploration #1034_Brief Explanation
  01-intro.Rmd
  book.bib
Labels: enhancement

#1197 Section 7.1 phase-2 initial round changes
  06-conclusion.Rmd
Labels: bug, enhancement

#1193 Add content to fix issue #897
  03-casestudies.Rmd
Labels: enhancement

#1214 Updates to book.bib
  02-fundamentals.Rmd
  05-ethics.Rmd
  book.bib
Labels: reference issue

#1219 some more refinements to section 7.1 based on issue#1196
  06-conclusion.Rmd
  book.bib
Labels: enhancement

#1202 Fixed issue #1200
  04-patterns.Rmd
Labels: enhancement

#1255 prerequisite initial commit
  06-process.Rmd
  book.bib
Labels: enhancement

#1256 Fixed picture bugs #1251
  04-patterns.Rmd
  images/renew1.png
  images/renew2.png
  images/renew3.png
Labels: bug

#1285 Reorganized the important prerequisites
  06-process.Rmd
Labels: enhancement

#1277 Data viz project issue1247
  06-process.Rmd
  book.bib
  docs/how-to-run-a-data-viz-project.html
  docs/images/OperationalDash_MSF.png
  docs/images/RP8Image10.png
  docs/images/RP8Image8.png
  docs/images/RP8Image9.png
  docs/images/StrategicDash_MSF.png
  docs/images/viz_example.png
  docs/search_index.json
  images/OperationalDash_MSF.png
  images/RP8Image10.PNG
  images/RP8Image8.PNG
  images/RP8Image9.PNG
  images/StrategicDash_MSF.png
  images/geography_matters.png
  images/viz_example.png
Labels: enhancement

#1299 Fixed few formatting issues in Chapter-6 "Important Prerequisites"
  06-process.Rmd
Labels: enhancement

#1313 Add new graph to fix the broken graph 6.5
  06-process.Rmd
  images/geography_matters.png
Labels: bug
