Repository mschermann/data_viz_reader, pull requests merged in 2019-06, with the labels that each got.

#1311 Formatting section 6.1 issue#1231
  06-process.Rmd
Labels: bug

#1357 Content enhancement for Case Study
  06-process.Rmd
  book.bib
Labels: enhancement

#1310 Add new graphs for chapter 4.7.8 and 4.7.9
  06-process.Rmd
  images/Basemap.png
  images/Bokeh.png
  images/Leaflet.png
  images/NetworkX.png
  images/Seaborn.png
  images/d3js.png
  images/ggplot2.png
  images/ggvis.png
  images/matplotlib.png
  images/tableau_a.png
Labels: enhancement

#1361 Adding new content on 6.4.1
  06-process.Rmd
  book.bib
Labels: enhancement

#1343 Format Fix For the case study
  06-process.Rmd
Labels: enhancement

#1362 Further Introduction updates Issue #1229
  06-process.Rmd
Labels: enhancement

#1415 Chapter was interrupted by a title for 6.7.4
  06-process.Rmd
Labels: bug

#1494 Fix for issue #1493
  06-process.Rmd
Labels: roadmap

#1492 Fixed 6.2.2 Grammar Mistakes
  06-process.Rmd
Labels: enhancement, roadmap

#1491 Fixing issue #1490
  03-casestudies.Rmd
Labels: roadmap

#1396 Fix issue #1389
  06-process.Rmd
  images/Data_studio.png
  images/Excel.png
  images/Google.jpg
  images/Ploty.png
  images/Raw.png
Labels: enhancement
